apiVersion: v2
name: collector
description: A Helm chart for Better Stack Collector - monitoring solution that collects metrics, logs, and traces
type: application
version: 0.1.10
appVersion: "latest"
keywords:
  - monitoring
  - metrics
  - logs
  - traces
  - observability
  - ebpf
  - tracing
  - logging
  - betterstack
  - better-stack
  - better-stack-collector
maintainers:
  - name: Better Stack
    email: hello@betterstack.com
    url: https://betterstack.com
home: https://betterstack.com
icon: https://avatars.githubusercontent.com/u/85562337
sources:
  - https://github.com/BetterStackHQ/collector-helm-chart
