{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "better-stack-collector.serviceAccountName" . }}
  labels:
    {{- include "better-stack-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: better-stack-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "better-stack-collector.fullname" . }}
  labels:
    {{- include "better-stack-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: better-stack-collector
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/stats
  - services
  - endpoints
  - pods
  - pods/log
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - nodes
  - pods
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "better-stack-collector.fullname" . }}
  labels:
    {{- include "better-stack-collector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "better-stack-collector.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "better-stack-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}